= Pre-configured Firma Digital Web Services with Wildfly 20 + Postgres 11

== Postgres

This image is based on the [official Postgres image](https://hub.docker.com/_/postgres)

=== Configuration

Set required `max_prepared_transactions` setting required by Bonita.

=== Databases

When starting a new container, it will create two databases...
* `bonita` (connection user `bonita`, password `bpm`)
* `business_data` (connection user `business_data`, password `bpm`)

=== Build and run it

- First create an `.env` file similar to the `.env-example` file and configure it with the respective credentials.

[source, bash]
----
docker build -t my-bonita-postgres .
----

Recommended way, to have datafiles out of container: bind a volume to **/var/lib/postgresql/data**

[source, bash]
----
docker run -d \
    --name dev-postgres \
    -e POSTGRES_PASSWORD=postgres \
    -e PGDATA=/var/lib/postgresql/data/pgdata \
    -v ${HOME}/postgres-data/:/var/lib/postgresql/data \
    -p 5432:5432 \
    firmaec-postgres
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-postgres bash
----

Verify that the user and database have been created correctly:

[source, sql]
----
psql -d firmadigital -h 127.0.0.1 -U firmadigital
-- Expected return: 1
SELECT 1; \q
----

=== Review configurations in container (optional)

[source, bash]
----
cat /var/lib/postgresql/data/pgdata/postgresql.conf
cat /var/lib/postgresql/data/pgdata/pg_hba.conf
----


== Wildfly

=== Build and run it

- First create an `.env` file similar to the .env-example file and configure it with the respective credentials.

- Next, build images and run containers with Docker Compose:

[source, bash]
----
docker-compose up --build -d
----

Stop and remove containers, networks.

[source, bash]
----
docker-compose down -v --remove-orphans
----

=== Shell

Execute shell command inside container

[source, bash]
----
docker exec -it dev-wildfly bash
----
