version: '3.9'

services:  
  db:
    build: ./bonita-postgres
    container_name: dev-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data

  bonita:
    image: bonita:2021.1
    container_name: dev-bonita
    ports:
      - 8080:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_VENDOR=postgres
      - DB_HOST=db
      - TENANT_LOGIN=${TENANT_LOGIN}
      - TENANT_PASSWORD=${TENANT_PASSWORD}
      - PLATFORM_LOGIN=${PLATFORM_LOGIN}
      - PLATFORM_PASSWORD=${PLATFORM_PASSWORD}
      - REST_API_DYN_AUTH_CHECKS=false
      - TZ=America/Guayaquil
    volumes:
      - /opt/bonita:/opt/bonita
     
    restart: on-failure:2
    depends_on:
      - db
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh
