version: "3.9"

services:
  bonita:
    image: bonita:2021.1
    container_name: dev-bonita
    ports:
      - 5000:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_VENDOR=postgres
      - DB_HOST=db
      - TENANT_LOGIN=${TENANT_LOGIN}
      - TENANT_PASSWORD=${TENANT_PASSWORD}
      - PLATFORM_LOGIN=${PLATFORM_LOGIN}
      - PLATFORM_PASSWORD=${PLATFORM_PASSWORD}
      - REST_API_DYN_AUTH_CHECKS=false
      - TZ=America/Guayaquil
      - DB_NAME=${DB_NAME_BONITA}
      - DB_USER=${DB_USER_BONITA}
      - DB_PASS=${DB_PASS_BONITA}
      - BIZ_DB_NAME=${BIZ_DB_NAME_BONITA}
      - BIZ_DB_USER=${DB_USER_BONITA}
      - BIZ_DB_PASS=${DB_PASS_BONITA}
    volumes:
      - /opt/bonita:/opt/bonita

    restart: on-failure:2
    depends_on:
      - db
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh
