services:
  wildfly:
    build:
      context: ./wildfly
      dockerfile: Dockerfile-prod      
      args:
        - DB_USER_SIGNATURE=${DB_USER_SIGNATURE}
        - DB_PASS_SIGNATURE=${DB_PASS_SIGNATURE}
        - DB_NAME_SIGNATURE=${DB_NAME_SIGNATURE}
        - ADMIN_NAME=${ADMIN_NAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - JWT_KEY_SIGNATURE=${JWT_KEY_SIGNATURE}
    extra_hosts:
      - "dockerhost:192.168.100.119"
#      - "host.docker.internal:host-gateway"
#      - "host.docker.internal:172.17.0.1"
    container_name: wildfly-prod    
    restart: always
    ports:
      - 7776:7776
      - 9990:9990
    volumes:
      - wildfly-static:/opt/wildfly-static

volumes:
    wildfly-static:
      external: true
      # Create the volume externally using: docker volume create --name=wildfly-static
