= Pre-configured Bonita Runtime 2021.2 + Postgres 12.8 and Firma Digital Web Services with Wildfly 20

== Prerequisites

- Installing Docker and Docker Compose V2
- Create a copy of the `.env-example` file and rename it to `.env`, then modify it with the respective credentials.

== Postgres

This image is based on the https://hub.docker.com/_/postgres[official Postgres image]

=== Databases

When a new container is started, three databases will be created with the names and credentials provided in the `.env` file. For example:

* `bonita_db` (connection user `bonita_user`, password `bonita_pass`)
* `business_db` (connection user `bonita_user`, password `bonita_pass`)
* `signature_db` (connection user `user_db_sign`, password `password_db_sign`)

Recommended way, to have datafiles out of container: bind a volume to **/var/lib/postgresql/data**

=== Build and run it

Build images and run containers with Docker Compose:

[source, bash]
----
docker compose -f docker-compose-postgres.yml up --build -d
----

In case you want to stop and delete the networks and containers of the services defined in the Compose file run:

[source, bash]
----
docker compose -f docker-compose-postgres.yml down -v --remove-orphans
----

For additional configurations, please review the following files:

[source, bash]
----
docker exec -it dev-postgres bash
cat /var/lib/postgresql/data/pgdata/postgresql.conf
cat /var/lib/postgresql/data/pgdata/pg_hba.conf
----

== 05-14-2022
docker exec -it dev-postgres bash
psql bonita_bdm bonita_db_user
\dt
select count(*) from botipocertevento;
select count(*) from objetoevento;

truncate table objetoevento;
-- Para eliminar datos de una tabla y otras tablas que tienen una clave externa
-- que hace referencia a la tabla, use CASCADE
truncate table botipocertevento CASCADE;
-- NOTICE:  truncate cascades to table "objetoevento"
truncate table objetosolicitud;
truncate table objetocertificado CASCADE;
-- NOTICE:  truncate cascades to table "objetosolicitud"
-- NOTICE:  truncate cascades to table "objetocertific_prerrequisitos"
truncate table objetocertotros;
truncate table objetopracticas;
truncate table objetoprimeraprorroga;
truncate table objetoprorrogapago;

truncate table boparametros;


== 29-07-2022
truncate table boprerrequisito CASCADE;
NOTICE:  truncate cascades to table "objetocertific_prerrequisitos"
...
...

truncate table objetocertificado CASCADE;
-- NOTICE:  truncate cascades to table "objetosolicitud"
-- NOTICE:  truncate cascades to table "objetocertific_prerrequisitos"




== Wildfly

This image is based on the https://hub.docker.com/r/jboss/wildfly[official Wildfly image]

=== Build and run it

Build images and run containers with Docker Compose:

[source, bash]
----
docker volume create --name=wildfly-static
docker compose -f docker-compose-wildfly.yml up --build -d
    
# Prod without db
# docker volume create --name=wildfly-static
# docker-compose --env-file ./.env-wildfly-prod -f docker-compose-wildfly-prod.yml up --build -d
----

In case you want to stop and delete the networks and containers of the services defined in the Compose file run:

[source, bash]
----
docker compose -f docker-compose-wildfly.yml down -v --remove-orphans

# Prod without db
# docker compose -f docker-compose-wildfly-prod.yml down -v --remove-orphans
----


=== Post configuration Wildfly instance

Generate a SHA256 hash from a api key

*Opción 1:*.- You can use the following commands to generate your SHA256 hash:

[source, sql]
----
echo "The api key to use in this example is: secure_password"
export API_KEY_HASH=$(echo -n secure_password | sha256sum | cut -d' ' -f1)
echo -e "The SHA256 hash generated from the api key, which will be inserted in the database, is:\n$API_KEY_HASH"
----

**Opción 2:**.- You can also use https://hash.online-convert.com/es/generador-sha256[this page] to generate your SHA256 hash.

Insert the following record in the `sistema` table of the database `signature_db` (for development or production)

[source, sql]
----
docker exec -it dev-postgres bash
psql signature_db user_db_sign

INSERT INTO sistema(id, url, apikey, apikeyrest, descripcion, nombre) VALUES (1, 'http://localhost:7776/recepcion/rest', '$API_KEY_HASH', '$API_KEY_HASH', 'Módulo de certificación electrónica', 'mce');
----


== Bonita

=== Build and run it

Build and run it with Docker Compose. Build images before starting containers:

[source, bash]
----
docker volume create --name=bonita-vol
docker compose -f docker-compose-bonita.yml up --build -d
----

In case you want to stop and delete the networks and containers of the services defined in the Compose file run:

[source, bash]
----
docker compose -f docker-compose-bonita.yml down -v --remove-orphans
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-bonita bash 
----

=== Post configuration Bonita Runtime (Optional)

Download and replace Bonita login page.

[source, bash]
----
wget https://github.com/alexjcm/certificacion-electronica-recursos/raw/main/01_paginas/bonita-pages/login.jsp \
  && mv -f login.jsp /var/lib/docker/volumes/bonita-vol/_data/BonitaCommunity-2021.2-u0/server/webapps/bonita
----

