= Pre-configured Bonita Runtime + Postgres 11 and Firma Digital Web Services with Wildfly

== Prerequisites

- Create an `.env` file similar to the `.env-example` file and configure it with the respective credentials.

== Postgres

This image is based on the https://hub.docker.com/_/postgres[official Postgres image]

=== Databases

When a new container is started, three databases will be created with the names and credentials provided in the `.env` file.

* `bonita_db` (connection user `bonita_user`, password `bonita_pass`)
* `business_db` (connection user `bonita_user`, password `bonita_pass`)
* `signature_db` (connection user `user_db_sign`, password `password_db_sign`)

Recommended way, to have datafiles out of container: bind a volume to **/var/lib/postgresql/data**

=== Review configurations in container (optional)

----
cat /var/lib/postgresql/data/pgdata/postgresql.conf
cat /var/lib/postgresql/data/pgdata/pg_hba.conf
----


== Wildfly

This image is based on the https://hub.docker.com/r/jboss/wildfly[official Wildfly image]

=== Build and run it

Build images and run containers with Docker Compose:

[source, bash]
----
docker volume create --name=wildfly-static \
    && docker-compose -f docker-compose-wildfly.yml up --build -d
----

Stop and remove networks and containers for services defined in the Compose file.

[source, bash]
----
docker-compose -f docker-compose-wildfly.yml down -v --remove-orphans
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-wildfly bash
----

=== Post configuration Wildfly instance

Generate a SHA256 hash from a api key

- You can use the following commands to generate your SHA256 hash:

[source, sql]
----
echo "The api key to use in this example is: secure_password"
export API_KEY_HASH=$(echo -n secure_password | sha256sum | cut -d' ' -f1)
echo -e "The SHA256 hash generated from the api key, which will be inserted in the database, is:\n$API_KEY_HASH"
----

- You can also use https://hash.online-convert.com/es/generador-sha256[this page] to generate your SHA256 hash.

Insert the following record in the `sistema` table of the database `signature_db` (for development or production)

[source, sql]
----
psql signature_db user_db_sign

INSERT INTO sistema(id, url, apikey, apikeyrest, descripcion, nombre) VALUES (1, 'http://localhost:8080/recepcion/rest', '$API_KEY_HASH', '$API_KEY_HASH', 'Módulo de certificación electrónica', 'mce');
----


== Bonita

=== Build and run it

Build and run it with Docker Compose. Build images before starting containers:

[source, bash]
----
docker volume create --name=wildfly-static \
    && docker-compose -f docker-compose-bonita.yml up --build -d
----

Stop and remove networks and containers for services defined in the Compose file.

[source, bash]
----
docker-compose -f docker-compose-bonita.yml down -v --remove-orphans
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-bonita bash
----

=== Post configuration Bonita Runtime (Optional)

Download and configure bonita error pages.

[source, bash]
----
export URL_PAGES=https://github.com/alexjcm/certificacion-electronica-recursos/raw/main/01_paginas/bonita-pages \
  && export PATH_BONITA_SERVER=/opt/bonita/BonitaCommunity-2021.1/server \
  && wget $URL_PAGES/login.jsp \
  && mv -f login.jsp $PATH_BONITA_SERVER/webapps/bonita \
  && wget $URL_PAGES/error-pages/403.jsp \
  && wget $URL_PAGES/error-pages/404.jsp \
  && wget $URL_PAGES/error-pages/500.jsp \
  && mv -f 403.jsp 404.jsp 500.jsp $PATH_BONITA_SERVER/webapps/bonita/error-pages
----
