= Pre-configured Bonita Runtime + Postgres 11 and Firma Digital Web Services with Wildfly

== Prerequisites

- Create an `.env` file similar to the `.env-example` file and configure it with the respective credentials.

== Postgres

This image is based on the https://hub.docker.com/_/postgres[official Postgres image]

=== Databases

When starting a new container, it will create three databases...
* `bonita` (connection user `bonita`, password `bpm`)
* `business_data` (connection user `business_data`, password `bpm`)
* `firmadigital` (connection user `firmadigital`, password `firmadigital`)

Recommended way, to have datafiles out of container: bind a volume to **/var/lib/postgresql/data**

=== Review configurations in container (optional)

[source, bash]
----
cat /var/lib/postgresql/data/pgdata/postgresql.conf
cat /var/lib/postgresql/data/pgdata/pg_hba.conf
----


== Wildfly

This image is based on the https://hub.docker.com/r/jboss/wildfly[official Wildfly image]

=== Build and run it

- Build images and run containers with Docker Compose:

[source, bash]
----
docker volume create --name=wildfly-static
docker-compose -f docker-compose-wildfly.yml up --build -d
----

Stop and remove networks and containers for services defined in the Compose file.

[source, bash]
----
docker-compose -f docker-compose-wildfly.yml down -v --remove-orphans
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-wildfly bash
----


== Bonita

=== Build and run it

- Build and run it with Docker Compose. Build images before starting containers:

[source, bash]
----
docker-compose -f docker-compose-bonita.yml up --build -d
----

Stop and remove networks and containers for services defined in the Compose file.

[source, bash]
----
docker-compose -f docker-compose-bonita.yml down -v --remove-orphans
----

=== Execute shell command inside container

[source, bash]
----
docker exec -it dev-bonita bash
----

=== Post-Config Bonita (Optional)

Download and configure bonita error pages.

[source, bash]
----
export URL_PAGES=https://github.com/alexjcm/certificacion-electronica-recursos/raw/main/01_paginas/bonita-pages \
  && export PATH_BONITA_SERVER=/opt/bonita/BonitaCommunity-2021.1/server \
  && wget $URL_PAGES/login.jsp \
  && mv -f login.jsp $PATH_BONITA_SERVER/webapps/bonita \
  && wget $URL_PAGES/error-pages/403.jsp \
  && wget $URL_PAGES/error-pages/404.jsp \
  && wget $URL_PAGES/error-pages/500.jsp \
  && mv -f 403.jsp 404.jsp 500.jsp $PATH_BONITA_SERVER/webapps/bonita/error-pages
----
